# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0005_song_simple_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumRelation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('track_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowRelation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('track_position', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_01',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_02',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_03',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_04',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_05',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_06',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_07',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_08',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_09',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_10',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_11',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_12',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_13',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_14',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_15',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_16',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_17',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_18',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_19',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_track_20',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_01',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_02',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_03',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_04',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_05',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_06',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_07',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_08',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_09',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_10',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_11',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_12',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_13',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_14',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_15',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_16',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_17',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_18',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_19',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_track_20',
        ),
        migrations.AddField(
            model_name='showrelation',
            name='show',
            field=models.ForeignKey(to='setlists.Show'),
        ),
        migrations.AddField(
            model_name='showrelation',
            name='song',
            field=models.ForeignKey(to='setlists.Song'),
        ),
        migrations.AddField(
            model_name='albumrelation',
            name='album',
            field=models.ForeignKey(to='setlists.Album'),
        ),
        migrations.AddField(
            model_name='albumrelation',
            name='song',
            field=models.ForeignKey(to='setlists.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_tracks',
            field=models.ManyToManyField(to='setlists.Song', through='setlists.AlbumRelation'),
        ),
        migrations.AddField(
            model_name='show',
            name='show_tracks',
            field=models.ManyToManyField(to='setlists.Song', through='setlists.ShowRelation'),
        ),
    ]
